
use crate::days::Solution;

#[derive(Debug)]
pub struct DayNUMBER {
    // State generated by `parse_input`
}

impl DayNUMBER {
    // Needed for creating a blank day
    pub fn new() -> DayNUMBER {
        todo!()
    }
}

impl Solution for DayNUMBER {
    fn reset(&mut self) {
        // Should probably do the same thing new() does.
        todo!()
    }

    fn parse_input(&mut self, file_contents: &str) {
        todo!()
    }

    fn part1(&self) -> String {
        todo!()
    }

    fn part2(&self) -> String {
        todo!()
    }
}
